"""
Email store — ChromaDB-backed vector store for persisting and retrieving
processed email records. Enables semantic search across past referrals,
billing events, and chat interactions without sending data off-device.

Two collections are maintained:
  ``email_records``   — full processed email records (JSON documents)
  ``email_summaries`` — short LLM-generated summaries for few-shot context
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import Any

import chromadb
from chromadb.config import Settings as ChromaSettings
from loguru import logger


CHROMA_PERSIST_DIR = "./chroma_db"
COLLECTION_NAME = "email_records"
SUMMARIES_COLLECTION_NAME = "email_summaries"


class EmailStore:
    """
    Persist email records and summaries in local ChromaDB collections.
    Records are stored as JSON documents; summaries are stored as plain text.
    Embeddings are generated by ChromaDB's default sentence-transformer
    (runs fully on-device).
    """

    def __init__(self, persist_dir: str = CHROMA_PERSIST_DIR) -> None:
        self._client = chromadb.PersistentClient(
            path=persist_dir,
            settings=ChromaSettings(anonymized_telemetry=False),
        )
        self._collection = self._client.get_or_create_collection(
            name=COLLECTION_NAME,
            metadata={"hnsw:space": "cosine"},
        )
        self._summaries = self._client.get_or_create_collection(
            name=SUMMARIES_COLLECTION_NAME,
            metadata={"hnsw:space": "cosine"},
        )
        logger.info(
            "EmailStore initialised (records={}, summaries={})",
            self._collection.count(),
            self._summaries.count(),
        )

    # ------------------------------------------------------------------
    # Full record write / read
    # ------------------------------------------------------------------

    def save(self, record: dict[str, Any]) -> str:
        """
        Persist *record* and return its document ID.

        *record* should contain at minimum:
          - ``raw``: original email text
          - ``type``: ``"referral"``, ``"billing"``, or ``"chat"``
          - ``structured``: parsed data dict (may be empty)
        """
        doc_id = self._make_id(record)
        document = json.dumps(record, default=str)
        metadata = {
            "type": record.get("type", "unknown"),
            "saved_at": datetime.now(timezone.utc).isoformat(),
        }

        self._collection.upsert(
            ids=[doc_id],
            documents=[document],
            metadatas=[metadata],
        )
        logger.debug("Saved email record id={} type={}", doc_id, metadata["type"])
        return doc_id

    def search(self, query: str, n_results: int = 5, record_type: str | None = None) -> list[dict]:
        """
        Semantic search over stored records.

        Args:
            query:       Natural-language search string.
            n_results:   Maximum number of results to return.
            record_type: Filter by ``"referral"``, ``"billing"``, or ``"chat"``.

        Returns:
            List of matching record dicts, most similar first.
        """
        where = {"type": record_type} if record_type else None
        results = self._collection.query(
            query_texts=[query],
            n_results=min(n_results, max(self._collection.count(), 1)),
            where=where,
        )

        records: list[dict] = []
        for doc in results.get("documents", [[]])[0]:
            try:
                records.append(json.loads(doc))
            except json.JSONDecodeError:
                records.append({"raw": doc})
        return records

    def get_by_id(self, doc_id: str) -> dict | None:
        """Retrieve a single record by its document ID."""
        result = self._collection.get(ids=[doc_id])
        docs = result.get("documents", [])
        if not docs:
            return None
        try:
            return json.loads(docs[0])
        except json.JSONDecodeError:
            return {"raw": docs[0]}

    def count(self) -> int:
        """Return the total number of stored records."""
        return self._collection.count()

    # ------------------------------------------------------------------
    # Summary write / read (few-shot context)
    # ------------------------------------------------------------------

    def save_summary(self, email_id: str, summary: str, classification: str) -> str:
        """
        Persist a short LLM-generated summary of a processed email for use
        as future few-shot context.  Full email bodies are never stored here —
        only the summary text.

        The document ID is derived from *email_id* so re-processing the same
        email updates the existing summary rather than creating a duplicate.

        PHI note: *summary* is caller-supplied.  Callers are responsible for
        ensuring the summary does not contain raw PHI — it should describe
        the nature of the email (type, action taken) without patient-level
        identifiers.

        Args:
            email_id:       Gmail message ID of the processed email.
            summary:        Short plain-text description of the email and
                            what action was taken (2–3 sentences max).
            classification: Classification category (``"referral"``,
                            ``"billing"``, ``"internal"``, ``"unknown"``).

        Returns:
            Document ID string.
        """
        doc_id = hashlib.sha256(email_id.encode()).hexdigest()[:32]
        metadata = {
            "email_id": email_id,
            "classification": classification,
            "saved_at": datetime.now(timezone.utc).isoformat(),
        }
        self._summaries.upsert(
            ids=[doc_id],
            documents=[summary],
            metadatas=[metadata],
        )
        logger.debug(
            "Saved email summary doc_id={} classification={}", doc_id, classification
        )
        return doc_id

    def get_similar_summaries(self, query_text: str, n: int = 3) -> list[str]:
        """
        Return up to *n* stored summaries whose content is semantically
        similar to *query_text*, ordered most-similar first.

        Used to provide few-shot examples when prompting the LLM for new
        emails of the same type.  Returns an empty list when the summaries
        collection is empty.

        Args:
            query_text: Text to search against (e.g. email subject + snippet).
            n:          Maximum number of summaries to return.

        Returns:
            List of summary strings, most similar first.
        """
        count = self._summaries.count()
        if count == 0:
            logger.debug("get_similar_summaries: summaries collection is empty")
            return []

        results = self._summaries.query(
            query_texts=[query_text],
            n_results=min(n, count),
        )

        summaries: list[str] = []
        for doc in results.get("documents", [[]])[0]:
            if doc:
                summaries.append(doc)

        logger.debug(
            "get_similar_summaries query returned {}/{} results", len(summaries), n
        )
        return summaries

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    @staticmethod
    def _make_id(record: dict) -> str:
        raw = record.get("raw", "") or json.dumps(record, default=str)
        return hashlib.sha256(raw.encode()).hexdigest()[:32]
